# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "gbarbieru/xenial"

  vagrant_host = "rancher-server"

  config.vm.hostname = vagrant_host

  config.vm.network :forwarded_port, 
    guest: 8080, 
    host: 8080,
    auto_correct: false

  config.vm.provider :virtualbox do |vb|
    vb.name = vagrant_host # set the virtual box name
    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024
  end

  config.vm.define vagrant_host # set the vagrant name (replace default)

  config.vm.provision "docker",
    type: "shell", 
    preserve_order: true,
    path: "../common/scripts/provision-docker.sh"

  config.vm.provision "rancher",
    type: "shell", 
    preserve_order: true,
    path: "../common/scripts/provision-rancher-server.sh",
    args: "#{`hostname`}"   
end
