# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "gbarbieru/xenial"

  vagrant_host = "rancher-host-1"

  config.vm.hostname = vagrant_host

  config.vm.network "forwarded_port", 
    guest: 8081, 
    host: 8081, 
    auto_correct: true

  config.vm.network "forwarded_port", 
    guest: 8082, 
    host: 8082, 
    auto_correct: true

  config.vm.network "forwarded_port", 
    guest: 8083, 
    host: 8083, 
    auto_correct: true

  config.vm.provider :virtualbox do |vb|
    vb.name = vagrant_host # set the virtual box name
    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024
  end

  config.vm.define vagrant_host # set the vagrant name (replace default)

  config.vm.provision "docker",
    type: "shell", 
    preserve_order: true,
    path: "../common/scripts/provision-docker.sh"

  config.vm.provision "rancher-host",
    type: "shell", 
    preserve_order: true,
    path: "../common/scripts/provision-rancher-host.sh",
    args: "#{`hostname`}"
end
